// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"errors"
)

const (
	// ForceLowerTypeDataSwap is a ForceLowerType of type DataSwap.
	ForceLowerTypeDataSwap ForceLowerType = iota
	// ForceLowerTypeBootNode is a ForceLowerType of type BootNode.
	ForceLowerTypeBootNode
)

var ErrInvalidForceLowerType = errors.New("not a valid ForceLowerType")

const _ForceLowerTypeName = "dataswapbootnode"

var _ForceLowerTypeMap = map[ForceLowerType]string{
	ForceLowerTypeDataSwap: _ForceLowerTypeName[0:8],
	ForceLowerTypeBootNode: _ForceLowerTypeName[8:16],
}

// String implements the Stringer interface.
func (x ForceLowerType) String() string { _ = "STUB: not implemented"; return "" }

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ForceLowerType) IsValid() bool { _ = "STUB: not implemented"; return false }

var _ForceLowerTypeValue = map[string]ForceLowerType{
	_ForceLowerTypeName[0:8]:  ForceLowerTypeDataSwap,
	_ForceLowerTypeName[8:16]: ForceLowerTypeBootNode,
}

// ParseForceLowerType attempts to convert a string to a ForceLowerType.
func ParseForceLowerType(name string) (ForceLowerType, error) {
	_ = "STUB: not implemented"
	return *new(ForceLowerType), nil
}
