// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"database/sql/driver"
	"errors"
)

const (
	// UnparsedSqlStringA is a UnparsedSqlString of type A.
	UnparsedSqlStringA UnparsedSqlString = "A"
	// UnparsedSqlStringB is a UnparsedSqlString of type B.
	UnparsedSqlStringB UnparsedSqlString = "B"
	// UnparsedSqlStringC is a UnparsedSqlString of type C.
	UnparsedSqlStringC UnparsedSqlString = "C"
	// UnparsedSqlStringD is a UnparsedSqlString of type D.
	UnparsedSqlStringD UnparsedSqlString = "D"
	// UnparsedSqlStringE is a UnparsedSqlString of type E.
	UnparsedSqlStringE UnparsedSqlString = "E"
)

var ErrInvalidUnparsedSqlString = errors.New("not a valid UnparsedSqlString")

// String implements the Stringer interface.
func (x UnparsedSqlString) String() string {
	_ = "STUB: not implemented"

	// IsValid provides a quick way to determine if the typed value is
	// part of the allowed enumerated values
	return ""
}

func (x UnparsedSqlString) IsValid() bool { _ = "STUB: not implemented"; return false }

var _UnparsedSqlStringValue = map[string]UnparsedSqlString{
	"A": UnparsedSqlStringA,
	"B": UnparsedSqlStringB,
	"C": UnparsedSqlStringC,
	"D": UnparsedSqlStringD,
	"E": UnparsedSqlStringE,
}

// parseUnparsedSqlString attempts to convert a string to a UnparsedSqlString.
func parseUnparsedSqlString(name string) (UnparsedSqlString, error) {
	_ = "STUB: not implemented"
	return *new(UnparsedSqlString), nil
}

var errUnparsedSqlStringNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *UnparsedSqlString) Scan(value interface{}) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// A wider range of scannable types.
// driver.Value values at the top of the list for expediency

// Value implements the driver Valuer interface.
func (x UnparsedSqlString) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

const (
	// UnparsedSqlValuesA is a UnparsedSqlValues of type A.
	UnparsedSqlValuesA UnparsedSqlValues = iota
	// UnparsedSqlValuesB is a UnparsedSqlValues of type B.
	UnparsedSqlValuesB
	// UnparsedSqlValuesC is a UnparsedSqlValues of type C.
	UnparsedSqlValuesC
	// UnparsedSqlValuesD is a UnparsedSqlValues of type D.
	UnparsedSqlValuesD
	// UnparsedSqlValuesE is a UnparsedSqlValues of type E.
	UnparsedSqlValuesE
)

var ErrInvalidUnparsedSqlValues = errors.New("not a valid UnparsedSqlValues")

const _UnparsedSqlValuesName = "ABCDE"

var _UnparsedSqlValuesMap = map[UnparsedSqlValues]string{
	UnparsedSqlValuesA: _UnparsedSqlValuesName[0:1],
	UnparsedSqlValuesB: _UnparsedSqlValuesName[1:2],
	UnparsedSqlValuesC: _UnparsedSqlValuesName[2:3],
	UnparsedSqlValuesD: _UnparsedSqlValuesName[3:4],
	UnparsedSqlValuesE: _UnparsedSqlValuesName[4:5],
}

// String implements the Stringer interface.
func (x UnparsedSqlValues) String() string { _ = "STUB: not implemented"; return "" }

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UnparsedSqlValues) IsValid() bool { _ = "STUB: not implemented"; return false }

var _UnparsedSqlValuesValue = map[string]UnparsedSqlValues{
	_UnparsedSqlValuesName[0:1]: UnparsedSqlValuesA,
	_UnparsedSqlValuesName[1:2]: UnparsedSqlValuesB,
	_UnparsedSqlValuesName[2:3]: UnparsedSqlValuesC,
	_UnparsedSqlValuesName[3:4]: UnparsedSqlValuesD,
	_UnparsedSqlValuesName[4:5]: UnparsedSqlValuesE,
}

// parseUnparsedSqlValues attempts to convert a string to a UnparsedSqlValues.
func parseUnparsedSqlValues(name string) (UnparsedSqlValues, error) {
	_ = "STUB: not implemented"
	return *new(UnparsedSqlValues), nil
}

var errUnparsedSqlValuesNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *UnparsedSqlValues) Scan(value interface{}) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// A wider range of scannable types.
// driver.Value values at the top of the list for expediency

// json marshals everything as a float64 if it's a number

// json marshals everything as a float64 if it's a number

// Value implements the driver Valuer interface.
func (x UnparsedSqlValues) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}
