// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"database/sql/driver"
	"errors"
)

const (
	// ImageTypeJpeg is a ImageType of type Jpeg.
	ImageTypeJpeg ImageType = iota
	// ImageTypeJpg is a ImageType of type Jpg.
	ImageTypeJpg
	// ImageTypePng is a ImageType of type Png.
	ImageTypePng
	// ImageTypeTiff is a ImageType of type Tiff.
	ImageTypeTiff
	// ImageTypeGif is a ImageType of type Gif.
	ImageTypeGif
)

var ErrInvalidImageType = errors.New("not a valid ImageType")

const _ImageTypeName = "jpegjpgpngtiffgif"

var _ImageTypeMap = map[ImageType]string{
	ImageTypeJpeg: _ImageTypeName[0:4],
	ImageTypeJpg:  _ImageTypeName[4:7],
	ImageTypePng:  _ImageTypeName[7:10],
	ImageTypeTiff: _ImageTypeName[10:14],
	ImageTypeGif:  _ImageTypeName[14:17],
}

// String implements the Stringer interface.
func (x ImageType) String() string { _ = "STUB: not implemented"; return "" }

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ImageType) IsValid() bool { _ = "STUB: not implemented"; return false }

var _ImageTypeValue = map[string]ImageType{
	_ImageTypeName[0:4]:   ImageTypeJpeg,
	_ImageTypeName[4:7]:   ImageTypeJpg,
	_ImageTypeName[7:10]:  ImageTypePng,
	_ImageTypeName[10:14]: ImageTypeTiff,
	_ImageTypeName[14:17]: ImageTypeGif,
}

// ParseImageType attempts to convert a string to a ImageType.
func ParseImageType(name string) (ImageType, error) {
	_ = "STUB: not implemented"
	return *new(ImageType), nil
}

var errImageTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ImageType) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// A wider range of scannable types.
// driver.Value values at the top of the list for expediency

// try parsing the integer value as a string

// try parsing the integer value as a string

// json marshals everything as a float64 if it's a number

// json marshals everything as a float64 if it's a number

// try parsing the integer value as a string

// Value implements the driver Valuer interface.
func (x ImageType) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

type NullImageType struct {
	ImageType ImageType
	Valid     bool
}

func NewNullImageType(val interface{}) (x NullImageType) {
	_ = "STUB: not implemented"
	// yes, we ignore this error, it will just be an invalid value.
	return *new(NullImageType)
}

// Scan implements the Scanner interface.
func (x *NullImageType) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// Value implements the driver Valuer interface.
func (x NullImageType) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

// driver.Value accepts int64 for int values.
