// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"database/sql/driver"
	"errors"
)

const (
	// JobStatePending is a JobState of type Pending.
	JobStatePending JobState = iota
	// JobStateProcessing is a JobState of type Processing.
	JobStateProcessing
	// JobStateCompleted is a JobState of type Completed.
	JobStateCompleted
	// JobStateFailed is a JobState of type Failed.
	JobStateFailed
)

var ErrInvalidJobState = errors.New("not a valid JobState")

const _JobStateName = "pendingprocessingcompletedfailed"

var _JobStateMap = map[JobState]string{
	JobStatePending:    _JobStateName[0:7],
	JobStateProcessing: _JobStateName[7:17],
	JobStateCompleted:  _JobStateName[17:26],
	JobStateFailed:     _JobStateName[26:32],
}

// String implements the Stringer interface.
func (x JobState) String() string { _ = "STUB: not implemented"; return "" }

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x JobState) IsValid() bool { _ = "STUB: not implemented"; return false }

var _JobStateValue = map[string]JobState{
	_JobStateName[0:7]:   JobStatePending,
	_JobStateName[7:17]:  JobStateProcessing,
	_JobStateName[17:26]: JobStateCompleted,
	_JobStateName[26:32]: JobStateFailed,
}

// ParseJobState attempts to convert a string to a JobState.
func ParseJobState(name string) (JobState, error) {
	_ = "STUB: not implemented"
	return *new(JobState), nil
}

var errJobStateNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *JobState) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// A wider range of scannable types.
// driver.Value values at the top of the list for expediency

// json marshals everything as a float64 if it's a number

// json marshals everything as a float64 if it's a number

// Value implements the driver Valuer interface.
func (x JobState) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

type NullJobState struct {
	JobState JobState
	Valid    bool
}

func NewNullJobState(val interface{}) (x NullJobState) {
	_ = "STUB: not implemented"
	// yes, we ignore this error, it will just be an invalid value.
	return *new(NullJobState)
}

// Scan implements the Scanner interface.
func (x *NullJobState) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// Value implements the driver Valuer interface.
func (x NullJobState) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}
