// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"database/sql/driver"
	"errors"
)

const (
	ProjectStatusPending ProjectStatus = iota
	ProjectStatusInWork
	ProjectStatusCompleted
	ProjectStatusRejected
)

var ErrInvalidProjectStatus = errors.New("not a valid ProjectStatus")

const _ProjectStatusName = "pendinginWorkcompletedrejected"

var _ProjectStatusMap = map[ProjectStatus]string{
	ProjectStatusPending:   _ProjectStatusName[0:7],
	ProjectStatusInWork:    _ProjectStatusName[7:13],
	ProjectStatusCompleted: _ProjectStatusName[13:22],
	ProjectStatusRejected:  _ProjectStatusName[22:30],
}

// String implements the Stringer interface.
func (x ProjectStatus) String() string { _ = "STUB: not implemented"; return "" }

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ProjectStatus) IsValid() bool { _ = "STUB: not implemented"; return false }

var _ProjectStatusValue = map[string]ProjectStatus{
	_ProjectStatusName[0:7]:   ProjectStatusPending,
	_ProjectStatusName[7:13]:  ProjectStatusInWork,
	_ProjectStatusName[13:22]: ProjectStatusCompleted,
	_ProjectStatusName[22:30]: ProjectStatusRejected,
}

// ParseProjectStatus attempts to convert a string to a ProjectStatus.
func ParseProjectStatus(name string) (ProjectStatus, error) {
	_ = "STUB: not implemented"
	return *new(ProjectStatus), nil
}

func (x ProjectStatus) Ptr() *ProjectStatus {
	_ = "STUB: not implemented"

	// MarshalText implements the text marshaller method.
	return nil
}

func (x ProjectStatus) MarshalText() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalText implements the text unmarshaller method.
func (x *ProjectStatus) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ProjectStatus) AppendText(b []byte) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var errProjectStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *ProjectStatus) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// A wider range of scannable types.
// driver.Value values at the top of the list for expediency

// try parsing the integer value as a string

// try parsing the integer value as a string

// json marshals everything as a float64 if it's a number

// json marshals everything as a float64 if it's a number

// try parsing the integer value as a string

// Value implements the driver Valuer interface.
func (x ProjectStatus) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus
	Valid         bool
	Set           bool
}

func NewNullProjectStatus(val interface{}) (x NullProjectStatus) {
	_ = "STUB: not implemented"
	// yes, we ignore this error, it will just be an invalid value.
	return *new(NullProjectStatus)
}

// Scan implements the Scanner interface.
func (x *NullProjectStatus) Scan(value interface{}) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// Value implements the driver Valuer interface.
func (x NullProjectStatus) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

// driver.Value accepts int64 for int values.

// MarshalJSON correctly serializes a NullProjectStatus to JSON.
func (n NullProjectStatus) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON correctly deserializes a NullProjectStatus from JSON.
func (n *NullProjectStatus) UnmarshalJSON(b []byte) error { _ = "STUB: not implemented"; return nil }

type NullProjectStatusStr struct {
	NullProjectStatus
}

func NewNullProjectStatusStr(val interface{}) (x NullProjectStatusStr) {
	_ = "STUB: not implemented"
	// yes, we ignore this error, it will just be an invalid value.
	return *new(NullProjectStatusStr)
}

// Value implements the driver Valuer interface.
func (x NullProjectStatusStr) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

// MarshalJSON correctly serializes a NullProjectStatus to JSON.
func (n NullProjectStatusStr) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON correctly deserializes a NullProjectStatus from JSON.
func (n *NullProjectStatusStr) UnmarshalJSON(b []byte) error { _ = "STUB: not implemented"; return nil }
