// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// Skipped value.
	_ GreekGod = "_"
	// GreekGodZeus is a GreekGod of type zeus.
	GreekGodZeus GreekGod = "zeus"
	// GreekGodApollo is a GreekGod of type apollo.
	GreekGodApollo GreekGod = "apollo"
	// GreekGodAthena is a GreekGod of type athena.
	GreekGodAthena GreekGod = "athena"
	// GreekGodAres is a GreekGod of type ares.
	GreekGodAres GreekGod = "ares"
)

var ErrInvalidGreekGod = fmt.Errorf("not a valid GreekGod, try [%s]", strings.Join(_GreekGodNames, ", "))

var _GreekGodNames = []string{
	string(GreekGodZeus),
	string(GreekGodApollo),
	string(GreekGodAthena),
	string(GreekGodAres),
}

// GreekGodNames returns a list of possible string values of GreekGod.
func GreekGodNames() []string { _ = "STUB: not implemented"; return nil }

// String implements the Stringer interface.
func (x GreekGod) String() string {
	_ = "STUB: not implemented"

	// IsValid provides a quick way to determine if the typed value is
	// part of the allowed enumerated values
	return ""
}

func (x GreekGod) IsValid() bool { _ = "STUB: not implemented"; return false }

var _GreekGodValue = map[string]GreekGod{
	"zeus":   GreekGodZeus,
	"apollo": GreekGodApollo,
	"athena": GreekGodAthena,
	"ares":   GreekGodAres,
}

// ParseGreekGod attempts to convert a string to a GreekGod.
func ParseGreekGod(name string) (GreekGod, error) {
	_ = "STUB: not implemented"
	return *new(GreekGod), nil
}

var errGreekGodNilPtr = errors.New("value pointer is nil") // one per type for package clashes

var sqlIntGreekGodMap = map[int64]GreekGod{
	1:  GreekGodZeus,
	2:  GreekGodApollo,
	20: GreekGodAthena,
	21: GreekGodAres,
}

var sqlIntGreekGodValue = map[GreekGod]int64{
	GreekGodZeus:   1,
	GreekGodApollo: 2,
	GreekGodAthena: 20,
	GreekGodAres:   21,
}

func lookupSqlIntGreekGod(val int64) (GreekGod, error) {
	_ = "STUB: not implemented"
	return *new(GreekGod), nil
}

// Scan implements the Scanner interface.
func (x *GreekGod) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// A wider range of scannable types.
// driver.Value values at the top of the list for expediency

// try parsing the value as a string

// json marshals everything as a float64 if it's a number

// json marshals everything as a float64 if it's a number

// Value implements the driver Valuer interface.
func (x GreekGod) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

type NullGreekGod struct {
	GreekGod GreekGod
	Valid    bool
}

func NewNullGreekGod(val interface{}) (x NullGreekGod) {
	_ = "STUB: not implemented"
	// yes, we ignore this error, it will just be an invalid value.
	return *new(NullGreekGod)
}

// make any errcheck linters happy

// Scan implements the Scanner interface.
func (x *NullGreekGod) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// Value implements the driver Valuer interface.
func (x NullGreekGod) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

// driver.Value accepts int64 for int values.

const (
	// Skipped value.
	_ GreekGodCustom = "_"
	// GreekGodCustomZeus is a GreekGodCustom of type zeus.
	GreekGodCustomZeus GreekGodCustom = "zeus"
	// GreekGodCustomApollo is a GreekGodCustom of type apollo.
	GreekGodCustomApollo GreekGodCustom = "apollo"
	// Skipped value.
	_ GreekGodCustom = "_"
	// GreekGodCustomAthena is a GreekGodCustom of type athena.
	GreekGodCustomAthena GreekGodCustom = "20"
	// GreekGodCustomAres is a GreekGodCustom of type ares.
	GreekGodCustomAres GreekGodCustom = "ares"
)

var ErrInvalidGreekGodCustom = fmt.Errorf("not a valid GreekGodCustom, try [%s]", strings.Join(_GreekGodCustomNames, ", "))

var _GreekGodCustomNames = []string{
	string(GreekGodCustomZeus),
	string(GreekGodCustomApollo),
	string(GreekGodCustomAthena),
	string(GreekGodCustomAres),
}

// GreekGodCustomNames returns a list of possible string values of GreekGodCustom.
func GreekGodCustomNames() []string { _ = "STUB: not implemented"; return nil }

// String implements the Stringer interface.
func (x GreekGodCustom) String() string {
	_ = "STUB: not implemented"

	// IsValid provides a quick way to determine if the typed value is
	// part of the allowed enumerated values
	return ""
}

func (x GreekGodCustom) IsValid() bool { _ = "STUB: not implemented"; return false }

var _GreekGodCustomValue = map[string]GreekGodCustom{
	"zeus":   GreekGodCustomZeus,
	"apollo": GreekGodCustomApollo,
	"20":     GreekGodCustomAthena,
	"ares":   GreekGodCustomAres,
}

// ParseGreekGodCustom attempts to convert a string to a GreekGodCustom.
func ParseGreekGodCustom(name string) (GreekGodCustom, error) {
	_ = "STUB: not implemented"
	return *new(GreekGodCustom), nil
}

var errGreekGodCustomNilPtr = errors.New("value pointer is nil") // one per type for package clashes

var sqlIntGreekGodCustomMap = map[int64]GreekGodCustom{
	1:  GreekGodCustomZeus,
	2:  GreekGodCustomApollo,
	20: GreekGodCustomAthena,
	21: GreekGodCustomAres,
}

var sqlIntGreekGodCustomValue = map[GreekGodCustom]int64{
	GreekGodCustomZeus:   1,
	GreekGodCustomApollo: 2,
	GreekGodCustomAthena: 20,
	GreekGodCustomAres:   21,
}

func lookupSqlIntGreekGodCustom(val int64) (GreekGodCustom, error) {
	_ = "STUB: not implemented"
	return *new(GreekGodCustom), nil
}

// Scan implements the Scanner interface.
func (x *GreekGodCustom) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// A wider range of scannable types.
// driver.Value values at the top of the list for expediency

// try parsing the value as a string

// json marshals everything as a float64 if it's a number

// json marshals everything as a float64 if it's a number

// Value implements the driver Valuer interface.
func (x GreekGodCustom) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

type NullGreekGodCustom struct {
	GreekGodCustom GreekGodCustom
	Valid          bool
}

func NewNullGreekGodCustom(val interface{}) (x NullGreekGodCustom) {
	_ = "STUB: not implemented"
	// yes, we ignore this error, it will just be an invalid value.
	return *new(NullGreekGodCustom)
}

// make any errcheck linters happy

// Scan implements the Scanner interface.
func (x *NullGreekGodCustom) Scan(value interface{}) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// Value implements the driver Valuer interface.
func (x NullGreekGodCustom) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

// driver.Value accepts int64 for int values.
