// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	StrStatePending   StrState = "pending"
	StrStateRunning   StrState = "running"
	StrStateCompleted StrState = "completed"
	StrStateFailed    StrState = "error"
)

var ErrInvalidStrState = fmt.Errorf("not a valid StrState, try [%s]", strings.Join(_StrStateNames, ", "))

var _StrStateNames = []string{
	string(StrStatePending),
	string(StrStateRunning),
	string(StrStateCompleted),
	string(StrStateFailed),
}

// StrStateNames returns a list of possible string values of StrState.
func StrStateNames() []string { _ = "STUB: not implemented"; return nil }

// StrStateValues returns a list of the values for StrState
func StrStateValues() []StrState { _ = "STUB: not implemented"; return nil }

// String implements the Stringer interface.
func (x StrState) String() string {
	_ = "STUB: not implemented"

	// IsValid provides a quick way to determine if the typed value is
	// part of the allowed enumerated values
	return ""
}

func (x StrState) IsValid() bool { _ = "STUB: not implemented"; return false }

var _StrStateValue = map[string]StrState{
	"pending":   StrStatePending,
	"running":   StrStateRunning,
	"completed": StrStateCompleted,
	"error":     StrStateFailed,
}

// ParseStrState attempts to convert a string to a StrState.
func ParseStrState(name string) (StrState, error) {
	_ = "STUB: not implemented"
	return *new(StrState), nil
}

// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.

// MustParseStrState converts a string to a StrState, and panics if is not valid.
func MustParseStrState(name string) StrState { _ = "STUB: not implemented"; return *new(StrState) }

func (x StrState) Ptr() *StrState {
	_ = "STUB: not implemented"

	// MarshalText implements the text marshaller method.
	return nil
}

func (x StrState) MarshalText() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalText implements the text unmarshaller method.
func (x *StrState) UnmarshalText(text []byte) error { _ = "STUB: not implemented"; return nil }

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *StrState) AppendText(b []byte) ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

var errStrStateNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *StrState) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// A wider range of scannable types.
// driver.Value values at the top of the list for expediency

// Value implements the driver Valuer interface.
func (x StrState) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *

	// Set implements the Golang flag.Value interface func.
	new(driver.Value), nil
}

func (x *StrState) Set(val string) error { _ = "STUB: not implemented"; return nil }

// Get implements the Golang flag.Getter interface func.
func (x *StrState) Get() interface{} {
	_ = "STUB: not implemented"

	// Type implements the github.com/spf13/pFlag Value interface.
	return nil
}

func (x *StrState) Type() string { _ = "STUB: not implemented"; return "" }

type NullStrState struct {
	StrState StrState
	Valid    bool
	Set      bool
}

func NewNullStrState(val interface{}) (x NullStrState) {
	_ = "STUB: not implemented"
	// yes, we ignore this error, it will just be an invalid value.
	return *new(NullStrState)
}

// make any errcheck linters happy

// Scan implements the Scanner interface.
func (x *NullStrState) Scan(value interface{}) (err error) { _ = "STUB: not implemented"; return nil }

// Value implements the driver Valuer interface.
func (x NullStrState) Value() (driver.Value, error) {
	_ = "STUB: not implemented"
	return *new(driver.Value), nil
}

// MarshalJSON correctly serializes a NullStrState to JSON.
func (n NullStrState) MarshalJSON() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalJSON correctly deserializes a NullStrState from JSON.
func (n *NullStrState) UnmarshalJSON(b []byte) error { _ = "STUB: not implemented"; return nil }
