// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

import (
	"errors"
)

const (
	// SuffixGen is a Suffix of type gen.
	SuffixGen Suffix = "gen"
)

var ErrInvalidSuffix = errors.New("not a valid Suffix")

// String implements the Stringer interface.
func (x Suffix) String() string {
	_ = "STUB: not implemented"

	// IsValid provides a quick way to determine if the typed value is
	// part of the allowed enumerated values
	return ""
}

func (x Suffix) IsValid() bool { _ = "STUB: not implemented"; return false }

var _SuffixValue = map[string]Suffix{
	"gen": SuffixGen,
}

// ParseSuffix attempts to convert a string to a Suffix.
func ParseSuffix(name string) (Suffix, error) { _ = "STUB: not implemented"; return *new(Suffix), nil }
